<?php

return array(
    'passportEditCharacter/([0-9]+)'=>'passport/editCharacter/$1',
    'passportsEditGeneralSave/([0-9]+)'=>'passport/editGeneralSave/$1',
    'passportEditGeneral/([0-9]+)'=>'passport/editGeneral/$1',
    'passportsNew'=>'passport/new',
    'passportFormGeneral'=>'passport/formGeneral',
    'editPassportMenu/([0-9]+)'=>'passport/editPassportMenu/$1',
    'passports'=>'passport/index',
    'admin2'=>'admin/level2',
    'errorAccess'=>'error/access',
    'questionDelete'=>'question/delete',
    'questionMarkUnAnswered'=>'question/markUnAnswered',
    'questionMarkAnswered'=>'question/markAnswered',
    'questionAddAnswer'=>'question/addAnswer',
    'questionAnswer/([0-9]+)'=>'question/answer/$1',
    'questionAdmin/([0-9]+)'=>'question/admin/$1',
    'addQuestion'=>'question/addQuestion',
    'question'=>'question/index',
    'auth'=>"admin/auth",
    'admin' => 'admin/index',
    '([a-zA-z0-9]+)' => 'site/index',
    '' => 'site/index',
    '(.+)'=>'site/index',
);